name: Inspect Pull Requests

on:
  pull_request:
    branches: [main]

jobs:
  bundlesize:
    if: ${{ always() }}
    needs: release-bundlesize
    runs-on: blacksmith-4vcpu-ubuntu-2204
    permissions:
      pull-requests: write
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: useblacksmith/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: |

          pnpm install
          npx lerna run build
          npx lerna run stats:pr --scope=@sassysaint/client
          npx lerna run stats:report --scope=@sassysaint/client
      - uses: mshick/add-pr-comment@v2
        if: always()
        with:
          refresh-message-position: true
          message-path: packages/client/tmp/pr-stats.md

  inspect:
    if: ${{ always() }}
    needs: release-bundlesize
    runs-on: blacksmith-4vcpu-ubuntu-2204
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: useblacksmith/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: |
          pnpm install
          npx lerna run build
          npx lerna run lint
          npx lerna run test

  release-bundlesize:
    if: github.head_ref == 'release-please--branches--main'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.NODE_CLI }}
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: useblacksmith/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: |
          pnpm install
          npx lerna run build
          npx lerna run stats:release --scope=@sassysaint/client
      - name: Commit Release Stats
        uses: stefanzweifel/git-auto-commit-action@v5
